lista_lenguajes_programacion = ["python","amazon","leverp","corea","person","los123"]
#print(lista_lenguajes_programacion)
#lista_lenguajes_programacion.append("lever")
#print(lista_lenguajes_programacion)
#lista_lenguajes_programacion.clear()
#print(lista_lenguajes_programacion)
#crear_lista_vacia = list()
#print(crear_lista_vacia)
#crear_lista_vacia = []
#print(crear_lista_vacia)
#print(lista_lenguajes_programacion.count("person"))
#lista_lenguajes_programacion.extend(["alamos","root","12"])
#print(lista_lenguajes_programacion)
#lista_tipos_variados = ["losrfd","lf458",2000,True]
#print(lista_tipos_variados)
#print(lista_lenguajes_programacion[1])
#lista_lenguajes_programacion.remove("python")
#print(lista_lenguajes_programacion)
#lista_lenguajes_programacion.reverse()
#print(lista_lenguajes_programacion)
#lista_lenguajes_programacion.pop(-1) 
#print(lista_lenguajes_programacion)
#lista_lenguajes_programacion.sort()
#print(lista_lenguajes_programacion)
#print(lista_lenguajes_programacion)
#print(lista_lenguajes_programacion[0:6:2])
print(lista_tipos_variados)
print(crear_lista_vacia)